apiVersion: v1beta1
desiredState:
  manifest:
    containers:
      - name: web
        image: dockerfile/nginx
        volumeMounts:
            # name must match the volume name below
            - name: nfs
              mountPath: "/var/www/html"
        ports:
          - name: web
            containerPort: 80
            protocol: tcp
    id: web
    version: v1beta1
    volumes:
      - name: nfs
        source:
          nfs:
            # FIXME: use the right name
            server: nfs-server.default.kube.local
            path: "/"
            readOnly: false
id: web
kind: Pod
